/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package latihangui;

/**
 *
 * @author Windows 10
 */
public class Biodata extends javax.swing.JFrame {

    /**
     * Creates new form Latihan4
     */
    public Biodata() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        b = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        rpl = new javax.swing.JRadioButton();
        tkj = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        alamat = new javax.swing.JTextField();
        absen = new javax.swing.JTextField();
        nama = new javax.swing.JTextField();
        combo = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("BIODATA SISWA");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(160, 20, 96, 14);

        jLabel2.setText("NAMA");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(50, 50, 40, 14);

        jLabel3.setText("ABSEN");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(50, 90, 40, 14);

        b.setText("KELAS");
        getContentPane().add(b);
        b.setBounds(50, 130, 40, 14);

        jLabel5.setText("JURUSAN");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(50, 170, 60, 14);

        jLabel6.setText("ALAMAT");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(50, 210, 60, 14);

        buttonGroup1.add(rpl);
        rpl.setText("RPL");
        getContentPane().add(rpl);
        rpl.setBounds(130, 170, 93, 23);

        buttonGroup1.add(tkj);
        tkj.setText("TKJ");
        getContentPane().add(tkj);
        tkj.setBounds(250, 170, 60, 23);

        jButton1.setText("SUBMIT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(330, 150, 69, 30);

        jButton2.setText("EXIT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(330, 190, 70, 30);
        getContentPane().add(alamat);
        alamat.setBounds(130, 200, 170, 30);
        getContentPane().add(absen);
        absen.setBounds(130, 80, 170, 30);
        getContentPane().add(nama);
        nama.setBounds(130, 40, 170, 30);

        combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "XRPL 1", "XRPL 2", "XRPL 3", "XRPL 4", "XRPL 5", "XRPL 6", "XRPL 7", "TKJ 1", "TKJ 2", "TKJ 3", "TKJ 4", "TKJ 5", "TKJ 6" }));
        getContentPane().add(combo);
        combo.setBounds(130, 130, 170, 20);

        setBounds(0, 0, 444, 339);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String nm,abs,jur,almt;
        String kelas = combo.getSelectedItem().toString();
        nm = nama.getText();
        abs = absen.getText();
        almt = alamat.getText();
        //jurusan
        if(rpl.isSelected()){
            jur = "RPL";
            if(combo.getSelectedItem()=="X RPL 1"){
            }
            if(combo.getSelectedItem()=="X RPL 2"){
            }
            if(combo.getSelectedItem()=="X RPL 3"){              
            }
            if(combo.getSelectedItem()=="X RPL 4"){
            }
            if(combo.getSelectedItem()=="X RPL 5"){
            }
            if(combo.getSelectedItem()=="X RPL 6"){
            }
            if(combo.getSelectedItem()=="X RPL 7"){
            }
        }else if(tkj.isSelected()){
            jur = "TKJ";
            if(combo.getSelectedItem()=="X TKJ 1"){
            }
            if(combo.getSelectedItem()=="X TKJ 2"){
            }
            if(combo.getSelectedItem()=="X TKJ 3"){
            }
            if(combo.getSelectedItem()=="X TKJ 4"){
            }
            if(combo.getSelectedItem()=="X TKJ 5"){
            }
            if(combo.getSelectedItem()=="X TKJ 6"){
            }
        }else jur = "";
        
        new HasilBiodata(nm,abs,jur,almt,kelas).setVisible(true);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Biodata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Biodata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Biodata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Biodata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Biodata().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField absen;
    private javax.swing.JTextField alamat;
    private javax.swing.JLabel b;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> combo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField nama;
    private javax.swing.JRadioButton rpl;
    private javax.swing.JRadioButton tkj;
    // End of variables declaration//GEN-END:variables
}
