/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package latihangui;

/**
 *
 * @author Windows 10
 */
public class Latihan2 extends javax.swing.JFrame {

    /**
     * Creates new form Latihan2
     */
    public Latihan2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Pilihanjurusan = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        varNama = new javax.swing.JTextField();
        varAbsen = new javax.swing.JTextField();
        rdbtkj = new javax.swing.JRadioButton();
        rdbrpl = new javax.swing.JRadioButton();
        CBEditing = new javax.swing.JCheckBox();
        CBProgramming = new javax.swing.JCheckBox();
        CBGaming = new javax.swing.JCheckBox();
        CBPhotograph = new javax.swing.JCheckBox();
        buttonSubmit = new javax.swing.JButton();
        buttonHapus = new javax.swing.JButton();
        buttonExit = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TAHasil = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("BIODATA");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(330, 30, 70, 20);

        jLabel2.setText("Nama");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(120, 60, 50, 20);

        jLabel3.setText("Absen");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(120, 100, 50, 20);

        jLabel4.setText("Jurusan");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(120, 140, 60, 20);

        jLabel5.setText("Hobi");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(120, 180, 40, 20);
        getContentPane().add(varNama);
        varNama.setBounds(240, 60, 270, 30);
        getContentPane().add(varAbsen);
        varAbsen.setBounds(240, 100, 270, 30);

        Pilihanjurusan.add(rdbtkj);
        rdbtkj.setText("TKJ");
        getContentPane().add(rdbtkj);
        rdbtkj.setBounds(240, 140, 60, 23);

        Pilihanjurusan.add(rdbrpl);
        rdbrpl.setText("RPL");
        getContentPane().add(rdbrpl);
        rdbrpl.setBounds(410, 140, 60, 23);

        CBEditing.setText("Editing");
        getContentPane().add(CBEditing);
        CBEditing.setBounds(240, 170, 70, 23);

        CBProgramming.setText("Programming");
        getContentPane().add(CBProgramming);
        CBProgramming.setBounds(410, 170, 90, 23);

        CBGaming.setText("Gaming");
        getContentPane().add(CBGaming);
        CBGaming.setBounds(240, 190, 70, 23);

        CBPhotograph.setText("Photograph");
        getContentPane().add(CBPhotograph);
        CBPhotograph.setBounds(410, 190, 90, 23);

        buttonSubmit.setText("Submit");
        buttonSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSubmitActionPerformed(evt);
            }
        });
        getContentPane().add(buttonSubmit);
        buttonSubmit.setBounds(240, 220, 65, 23);

        buttonHapus.setText("Remove");
        buttonHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonHapusActionPerformed(evt);
            }
        });
        getContentPane().add(buttonHapus);
        buttonHapus.setBounds(340, 220, 71, 23);

        buttonExit.setText("Exit");
        buttonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonExitActionPerformed(evt);
            }
        });
        getContentPane().add(buttonExit);
        buttonExit.setBounds(450, 220, 70, 23);

        jLabel6.setText("Hasil");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(120, 280, 40, 30);

        TAHasil.setColumns(20);
        TAHasil.setRows(5);
        jScrollPane1.setViewportView(TAHasil);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(230, 260, 300, 120);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/latihangui/Windows_10_Art_Logo_3840x2160.jpg"))); // NOI18N
        jLabel7.setText("jLabel7");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(168, 50, 4360, 370);

        setBounds(0, 0, 760, 432);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonExitActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_buttonExitActionPerformed

    private void buttonHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonHapusActionPerformed
        // TODO add your handling code here:
        varNama.setText("");
        varAbsen.setText("");
        Pilihanjurusan.clearSelection();
        TAHasil.setText("");
        CBEditing.setSelected(false);
        CBGaming.setSelected(false);
        CBProgramming.setSelected(false);
        CBPhotograph.setSelected(false);
        
    }//GEN-LAST:event_buttonHapusActionPerformed

    private void buttonSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSubmitActionPerformed
        // TODO add your handling code here:
        String nama = varNama.getText();
        String absen = varAbsen.getText();
        String jurusan;
        String hobi="";
        
        //untuk pilihan jurusan
        if (rdbrpl.isSelected())
            jurusan="RPL";
        else if (rdbtkj.isSelected())
            jurusan="TKJ";
        else
            jurusan=" ";
        
        //untuk pilihan checkbox
        if (CBEditing.isSelected())
            hobi+=CBEditing.getText()+",";
        if (CBGaming.isSelected())
            hobi+=CBGaming.getText()+",";
        if (CBProgramming.isSelected())
            hobi+=CBProgramming.getText()+",";
        if (CBPhotograph.isSelected())
            hobi+=CBPhotograph.getText()+",";
        
        //Untuk Hasil
        TAHasil.setText("Nama anda :" +nama+"\n Absen anda :"+absen+"\n Jurusan anda :"+jurusan+"\n Hobi anda :"+hobi);
    }//GEN-LAST:event_buttonSubmitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Latihan2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Latihan2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Latihan2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Latihan2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Latihan2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox CBEditing;
    private javax.swing.JCheckBox CBGaming;
    private javax.swing.JCheckBox CBPhotograph;
    private javax.swing.JCheckBox CBProgramming;
    private javax.swing.ButtonGroup Pilihanjurusan;
    private javax.swing.JTextArea TAHasil;
    private javax.swing.JButton buttonExit;
    private javax.swing.JButton buttonHapus;
    private javax.swing.JButton buttonSubmit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rdbrpl;
    private javax.swing.JRadioButton rdbtkj;
    private javax.swing.JTextField varAbsen;
    private javax.swing.JTextField varNama;
    // End of variables declaration//GEN-END:variables
}
